services:
  dev:
    build:
      context: ./.devcontainer
    volumes:
      - ./:/work
    working_dir: /work
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stonefruit?schema=public
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stonefruit
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    command: pnpm start
    volumes: ./:/work
    ports: 3000:3000
volumes:
  pgdata:
